# Collectd configuration for data collection
FROM newsdev/docker-collectd:coreos

MAINTAINER Mark Simms [masimms@microsoft.com]

ADD custom_collectd.conf /etc/collectd/collectd.d/custom_collectd.conf
